# Configuration for SpdVsHunt Plugins.

# SpdVsHunt Settings
# hunterBar: Turns on extra Information for Hunters on tracked speedrunners (such as distance and dimensions). /svh settings hunterBarInfo
# runnerCompass: Toggles speedrunner compass when there are more than one speedrunners, to track other speedrunners. /svh settings runnerCompass

options:
  hunterBar: 'false'
  runnerCompass: 'true'